package utils;

public enum NumbersValidatorResult {
    VALID_SELECTION,
    INVALID_NUMBER_OF_SELECTIONS,
    INVALID_RANGE_OF_SELECTIONS,
    DUPLICATE_SELECTION,
    ALPHANUMERIC_SELECTION,
    INVALID_GENERIC_SELECTION,
    MIN_SELECTED_NUMBER,
    MAX_SELECTED_NUMBER
}
